name: CI/CD Node Scotch

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  # JOB 1 : CI
  build-node-app:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests
        run: npm test

      - name: Vérification du code (Lint)
        run: npm run lint

  # JOB 2 : CD & Security (Ajout Trivy)
  push-docker-image:
    needs: build-node-app
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 1. On construit l'image d'abord pour pouvoir la scanner
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/examen-node:${{ github.sha }} .

      # 2. Scan de sécurité Trivy (NOUVEAU)
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/examen-node:${{ github.sha }}'
          format: 'table'
          exit-code: '0' # On met 0 pour ne pas bloquer l'examen si failles trouvées, mettre 1 pour bloquer en prod
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # 3. Si le scan est OK (ou informatif), on tag en latest et on push
      - name: Push Docker image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/examen-node:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/examen-node:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/examen-node:latest
