name: CI/CD Node Scotch

on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1 : Build de l'application (Vérification du code)
  build-node-app:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install

      # Le repo scotch-io a une commande "test" qui echo juste, mais on la lance pour valider le job
      - name: Lancer les tests
        run: npm test

  # JOB 2 : Build & Push Docker (Dépend du Job 1)
  push-docker-image:
    needs: build-node-app  # IMPORTANT : Ce job attend que le Job 1 soit fini (Vert)
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      # Étape de connexion (Défi 01)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape de Build et Push
      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-scotch-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-scotch-app:latest
